dat<-read.table("household_power_consumption.txt", header = T, sep=";", stringsAsFactors = F)
str(dat)
d1<-as.POSIXct('2007-02-01')
d2<-as.POSIXct('2007-02-02')
Index<-as.POSIXct(dat$Date , format = '%d/%m/%Y')
Index<-which(Index>=d1&Index<=d2)
dat<-dat[Index,]
str(dat)
gc()
dat$Global_active_power<-as.numeric(dat$Global_active_power)
dat$DateTime<-as.POSIXct(paste(dat$Date, dat$Time), format="%d/%m/%Y %H:%M:%S")
png("Plot3.PNG", width=480, height=480)
plot(dat$DateTime , dat$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", main="")
lines(dat$DateTime , dat$Sub_metering_2, col="red")
lines(dat$DateTime , dat$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col=c("black", "red", "blue"), cex=0.8, pch=20)
dev.off()
